### ISSUE TITLE
Tests have started to fail (with JSON::Schema::Modern 0.561?)

### ISSUE THREAD

**Issue by andk** [karenetheridge/OpenAPI-Modern#42]
Sample fail report: http://www.cpantesters.org/cpan/report/a98e9330-93d6-11ed-810b-43cad168a89d

Statistics suggest that JSON::Schema::Modern 0.561 is a strong candidate for a blame:

``` text
****************************************************************
Regression 'mod:JSON::Schema::Modern'
****************************************************************
Name                   Theta          StdErr     T-stat
[0='const']           1.0000          0.0000    32264009803194304.00
[1='eq_0.558']        0.0000          0.0000       5.40
[2='eq_0.559']        0.0000          0.0000       0.62
[3='eq_0.560']        0.0000          0.0000       1.88
[4='eq_0.561']       -1.0000          0.0000    -5533232032271860.00

R^2= 1.000, N= 154, K= 5
****************************************************************
```

**Comment by karenetheridge** [comment]
This is the first time I have seen the statistical analysis fail -- actually it was the release of Test::JSON::Schema::Acceptance 1.018 that was the culprit. I did release that nearly at the same time as JSON::Schema::Modern 0.561 though, so it would have been hard to tell one from the other.

Fixed in 0.038.

**Comment by karenetheridge** [comment]
hmm, perhaps not. it looks like there are two independent failures, one from new TJSA and one from new JSM.

**Comment by karenetheridge** [comment]
Now fixed.
